{"uid":"7d7856b9c9316ba4","name":"T33: Update an existing task with an invalid priority.","fullName":"tests.test_task_management.TestTaskManagement#test_update_task_with_invalid_priority","historyId":"fafa0064ecdb363ac8de4c6fb4cb98bc","time":{"start":1737378300307,"stop":1737378300972,"duration":665},"status":"failed","statusMessage":"AssertionError: Expected status code 400, but got 200. Response: {'status': 'success', 'task': {'_id': '678e49fd6eb12444f2b4685a', 'title': 'Law occur discover.', 'start': '12:14:28', 'end': '20:07:52', 'priority': 'add', 'category': 'done', 'owner': '678e49fc6eb12444f2b46856', 'date': '2025-01-11T00:00:00.000Z', 'createdAt': '2025-01-20T13:05:01.066Z', 'updatedAt': '2025-01-20T13:05:01.246Z', '__v': 0}}","statusTrace":"self = <test_task_management.TestTaskManagement object at 0x000001D25B465A30>\n\n    @pytest.mark.order(33)\n    @allure.title(\"T33: Update an existing task with an invalid priority.\")\n    def test_update_task_with_invalid_priority(self):\n        user = self.api_user_auth.create_user()\n        task = self.api_task.create_task(Token=user.data.accessToken)\n>       self.api_task.update_task_with_invalid_priority(Token=user.data.accessToken, task_id=task.id)\n\ntests\\test_task_management.py:83: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nservices\\Task\\api_task.py:160: in update_task_with_invalid_priority\n    self.assert_status(response, 400)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <services.Task.api_task.TaskAPI object at 0x000001D25B5EA780>, response = <Response [200]>, expected_status = 400\n\n    def assert_status(self, response, expected_status):\n>       assert response.status_code == expected_status, \\\n            (f\"Expected status code {expected_status}, but got {response.status_code}. Response: {response.json()}\")\nE       AssertionError: Expected status code 400, but got 200. Response: {'status': 'success', 'task': {'_id': '678e49fd6eb12444f2b4685a', 'title': 'Law occur discover.', 'start': '12:14:28', 'end': '20:07:52', 'priority': 'add', 'category': 'done', 'owner': '678e49fc6eb12444f2b46856', 'date': '2025-01-11T00:00:00.000Z', 'createdAt': '2025-01-20T13:05:01.066Z', 'updatedAt': '2025-01-20T13:05:01.246Z', '__v': 0}}\n\nutils\\helper.py:13: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1737378287248,"stop":1737378287249,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentStep":false,"hasContent":false,"shouldDisplayMessage":false,"attachmentsCount":0},{"name":"_xunit_setup_method_fixture_TestTaskManagement","time":{"start":1737378300306,"stop":1737378300306,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentStep":false,"hasContent":false,"shouldDisplayMessage":false,"attachmentsCount":0}],"testStage":{"status":"failed","statusMessage":"AssertionError: Expected status code 400, but got 200. Response: {'status': 'success', 'task': {'_id': '678e49fd6eb12444f2b4685a', 'title': 'Law occur discover.', 'start': '12:14:28', 'end': '20:07:52', 'priority': 'add', 'category': 'done', 'owner': '678e49fc6eb12444f2b46856', 'date': '2025-01-11T00:00:00.000Z', 'createdAt': '2025-01-20T13:05:01.066Z', 'updatedAt': '2025-01-20T13:05:01.246Z', '__v': 0}}","statusTrace":"self = <test_task_management.TestTaskManagement object at 0x000001D25B465A30>\n\n    @pytest.mark.order(33)\n    @allure.title(\"T33: Update an existing task with an invalid priority.\")\n    def test_update_task_with_invalid_priority(self):\n        user = self.api_user_auth.create_user()\n        task = self.api_task.create_task(Token=user.data.accessToken)\n>       self.api_task.update_task_with_invalid_priority(Token=user.data.accessToken, task_id=task.id)\n\ntests\\test_task_management.py:83: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nservices\\Task\\api_task.py:160: in update_task_with_invalid_priority\n    self.assert_status(response, 400)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <services.Task.api_task.TaskAPI object at 0x000001D25B5EA780>, response = <Response [200]>, expected_status = 400\n\n    def assert_status(self, response, expected_status):\n>       assert response.status_code == expected_status, \\\n            (f\"Expected status code {expected_status}, but got {response.status_code}. Response: {response.json()}\")\nE       AssertionError: Expected status code 400, but got 200. Response: {'status': 'success', 'task': {'_id': '678e49fd6eb12444f2b4685a', 'title': 'Law occur discover.', 'start': '12:14:28', 'end': '20:07:52', 'priority': 'add', 'category': 'done', 'owner': '678e49fc6eb12444f2b46856', 'date': '2025-01-11T00:00:00.000Z', 'createdAt': '2025-01-20T13:05:01.066Z', 'updatedAt': '2025-01-20T13:05:01.246Z', '__v': 0}}\n\nutils\\helper.py:13: AssertionError","steps":[{"name":"Create a new user.","time":{"start":1737378300307,"stop":1737378300616,"duration":309},"status":"passed","steps":[],"attachments":[{"uid":"fe9a5788b55333e6","name":"API Response","source":"fe9a5788b55333e6.json","type":"application/json","size":518}],"parameters":[],"stepsCount":0,"attachmentStep":false,"hasContent":true,"shouldDisplayMessage":false,"attachmentsCount":1},{"name":"Create a new task.","time":{"start":1737378300616,"stop":1737378300793,"duration":177},"status":"passed","steps":[],"attachments":[{"uid":"ffba098e18367b78","name":"API Response","source":"ffba098e18367b78.json","type":"application/json","size":350}],"parameters":[{"name":"Token","value":"'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OGU0OWZjNmViMTI0NDRmMmI0Njg1NiIsImlhdCI6MTczNzM3ODMwMCwiZXhwIjoxNzM3MzgxOTAwfQ.murPqAk3oKuhPxSjlFAZdHQ2samSkm2zRVOO1rP4Jhk'"}],"stepsCount":0,"attachmentStep":false,"hasContent":true,"shouldDisplayMessage":false,"attachmentsCount":1},{"name":"Update an existing task with an invalid priority.","time":{"start":1737378300793,"stop":1737378300971,"duration":178},"status":"failed","statusMessage":"AssertionError: Expected status code 400, but got 200. Response: {'status': 'success', 'task': {'_id': '678e49fd6eb12444f2b4685a', 'title': 'Law occur discover.', 'start': '12:14:28', 'end': '20:07:52', 'priority': 'add', 'category': 'done', 'owner': '678e49fc6eb12444f2b46856', 'date': '2025-01-11T00:00:00.000Z', 'createdAt': '2025-01-20T13:05:01.066Z', 'updatedAt': '2025-01-20T13:05:01.246Z', '__v': 0}}\n","statusTrace":"  File \"C:\\Users\\Pavlo\\Desktop\\Goose_Tracker_API_testing\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Pavlo\\Desktop\\Goose_Tracker_API_testing\\services\\Task\\api_task.py\", line 160, in update_task_with_invalid_priority\n    self.assert_status(response, 400)\n  File \"C:\\Users\\Pavlo\\Desktop\\Goose_Tracker_API_testing\\utils\\helper.py\", line 13, in assert_status\n    assert response.status_code == expected_status, \\\n","steps":[],"attachments":[],"parameters":[{"name":"Token","value":"'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OGU0OWZjNmViMTI0NDRmMmI0Njg1NiIsImlhdCI6MTczNzM3ODMwMCwiZXhwIjoxNzM3MzgxOTAwfQ.murPqAk3oKuhPxSjlFAZdHQ2samSkm2zRVOO1rP4Jhk'"},{"name":"task_id","value":"'678e49fd6eb12444f2b4685a'"}],"stepsCount":0,"attachmentStep":false,"hasContent":true,"shouldDisplayMessage":true,"attachmentsCount":0}],"attachments":[],"parameters":[],"stepsCount":3,"attachmentStep":false,"hasContent":true,"shouldDisplayMessage":true,"attachmentsCount":2},"afterStages":[{"name":"_xunit_setup_method_fixture_TestTaskManagement::0","time":{"start":1737378300982,"stop":1737378300982,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentStep":false,"hasContent":false,"shouldDisplayMessage":false,"attachmentsCount":0}],"labels":[{"name":"feature","value":"Task Management"},{"name":"tag","value":"order(33)"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_task_management"},{"name":"subSuite","value":"TestTaskManagement"},{"name":"host","value":"DESKTOP-0R2QBDF"},{"name":"thread","value":"848-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_task_management"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":["order(33)"]},"source":"7d7856b9c9316ba4.json","parameterValues":[]}